### ISSUE TITLE
Spelling Correction on English Documentation (ZXDOS+)

### ISSUE THREAD

**Issue by spectrumcomputing** [zxdos/zxuno#11]
Hi,

On page 4 of the English documentation

In order to use a microSD card, it has to be **formmatted** with

Should read In order to use a microSD card, it has to be **formatted** with

Also,

Page 39:

You can also use a second FAT16 partition for MSX software, and leaving the **firt** one only for the system startup.

Should read 'You can also use a second FAT16 partition for MSX software, and leaving the **first** one only for the system startup.'

Thanks

**Comment by kounch** [comment]
Fixed. Will be on the next revision.
