### ISSUE TITLE
Spelling Correction on English Documentation (ZXDOS+) - Miniduino

### ISSUE THREAD

**Issue by spectrumcomputing** [zxdos/zxuno#12]
Hi again,

Thanks for the excellent guide.  Its so good to have full documentation for a project!

It is also possible to play AY music files as if they **wer** tapes, in order to load the from
SpecAY in a ZX Spectrum.

Should be:

It is also possible to play AY music files as if they **were** tapes, in order to load the from
SpecAY in a ZX Spectrum.

**Comment by kounch** [comment]
Fixed for next revision. Thanks for the report
