### ISSUE TITLE
Binaries disappeared from repo

### ISSUE THREAD

**Issue by kounch** [zxdos/zxuno#43]
Some binaries are no more available, like CORCLEAN or COREBIOS and more. They were previously at the UTILS directory.
 
Regular users should have a place where they can obtain them without having to learn how to compile.

**Comment by ivan-tat** [comment]
Those files are still available in [`SD.zip`](SD.zip) - in `BIN` sud-directory inside it. I think it's a good idea to hold all recent binaries in one place to exclude outdated versions be available in different parts of this repo. If some sources will be modified - this archive should be updated. So, there should be some script for developers to automatically build and update this archive. If there's no such script then it should be created.

**Comment by kounch** [comment]
No. They are not at this moment (at least CORCLEAN and COREBIOS when i checked.

**Comment by ivan-tat** [comment]
Oh, I see. I'll put them in `SD/BIN` soon. This should be fixed automatically in the future by a script.

**Comment by kounch** [comment]
OK. I will update the manuals accordingly. At this moment they point out to the UTILS directory

**Comment by ivan-tat** [comment]
Uploaded missing binaries to `SD/BIN` in 6363bcb3197e8a48b62b658ebc4a5da388f9bae0. `SD.zip` left as-is for now. See https://github.com/zxdos/zxuno/issues/47
