### ISSUE TITLE
Should we add `ESPRST` and `IWCONFIG` to `SD/BIN` directory?

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#49]
These binary files are in `utils` directory but their sources are in `software/esprst` and `software/iwconfig` directories. I think it's better to move them inside `SD/BIN` for now or even delete and build from actual sources and then add to `SD/BIN`. Also, compiled `ESPRST` is of version 0.1, and sources are of version 0.2 in repo.

**Comment by antoniovillena** [comment]
Yes. You can move to SD/BIN

**Comment by ivan-tat** [comment]
Moved to `SD/BIN` with #64. Use `make` in the root of project to update (introduced with #63)
