### ISSUE TITLE
firmware: Missing sources of `Bit2Bin.exe`

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#57]
File's location: [`firmware/Bit2Bin.exe`](/zxdos/zxuno/blob/master/firmware/Bit2Bin.exe)
File's output:
```
Bit2Bin v0.05, strip .bit header and align binary to 16k, 2020-02-19

  Bit2Bin        <input_file> <output_file>

  <input_file>   Input BIT file
  <output_file>  Output BIN file

All params are mandatory
```
File's type: **binary**
File's license: **unknown**
Platform support: **Windows NT (Intel x86) only**
Linux, FreeBSD etc. platform support: **none**
This tools is used in scripts of `firmware` directory.
Sources are needed to use this tool on different from Windows NT platforms.

**Comment by antoniovillena** [comment]
Added on firmware/Bit2Bin.c. You can move to other folder if you want
