### ISSUE TITLE
Missing sources of `rcs.exe`

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#58]
File's location:
* [`hardware/kartusho/roms/rcs.exe`](/zxdos/zxuno/blob/master/hardware/kartusho/roms/rcs.exe)
* [`hardware/kartusho/snapshots/rcs.exe`](/zxdos/zxuno/blob/master/hardware/kartusho/snapshots/rcs.exe)

File's output:
```
rcs v1.03, SCR filter to RCS (and inverse) by Antonio Villena, 18 Jan 2013

  rcs [-i] <input_file> <output_file>

  -i             Inverse filter (RCS to SCR), optional
  <input_file>   Input file to filter
  <output_file>  Genetated output file

All params are mandatory except -i.
```
File's type: **binary**
File's license: **unknown**
Platform support: **Windows NT (Intel x86) only**
Linux, FreeBSD etc. platform support: **none**
This tool is used to process some files in `firmware` and others directories.
Sources are needed to use this tool on different from Windows NT platforms.

**Comment by antoniovillena** [comment]
Here is:

https://github.com/DSkywalk/fase/blob/master/ComplementosChurrera/FiltroRCS/rcs.c
