### ISSUE TITLE
firmware/scroll: Update credits to include forgotten contributors

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#69]
What about those **real** people, whose labor was used in the creation of ZX-Uno and of [`scroll`](https://github.com/zxdos/zxuno/tree/master/firmware/scroll) demo in particular? Let's see:

* In 2016 you used [`FuenteABin`](https://github.com/zxdos/zxuno/blob/master/firmware/scroll/FuenteABin.c) tool which uses sources of the project [`LodePNG`](https://github.com/lvandeve/lodepng), developed since 2005 by **Lode Vandevenne**. This tool is used to convert PNG image [`fuente6x8.png`](https://github.com/zxdos/zxuno/blob/master/firmware/scroll/fuente6x8.png) into a binary [`fuente6x8.bin`](https://github.com/zxdos/zxuno/blob/master/firmware/scroll/fuente6x8.bin) file used to show all of those credits on the screen in the `scroll` demo. But unfortunately there is no mention of him in that list of contributors. In the current state of the `scroll` demo without his work we could not even see any authors and contributors on the screen as like as the demo itself (no intermediate binary file - no final result);
* The team of [**SJAsmPlus Z80 compiler**](https://github.com/sjasmplus/sjasmplus). Widely used across the project;
* The team of [**Xilinx, Inc.**](https://www.xilinx.com/). Ross Freeman (co-founder of Xilinx, Inc.) has invented the field-programmable gate array (FPGA), which is the heart of ZX-Uno now.

I think we should pay respect to the work of these people (at least at the time of creating this demo). Will it be fair to mention them in the credits?

**Comment by ivan-tat** [comment]
Something like this will be fine, I think:
```
The team of lodepng project
The team of SJAsmPlus project
The team of Xilinx, Inc.
```

**Comment by antoniovillena** [comment]
Ok. I agree to mention all these people. Go ahead

**Comment by ivan-tat** [comment]
By the way should I add or you will add to the credits? I assigned you for this issue but I'm unclear who should add them. (And I've missed the team of Sinclair Research Ltd from view - parents of ZX Spectrum itself)

**Comment by antoniovillena** [comment]
You can add them to the credits

**Comment by ivan-tat** [comment]
I opened an issue https://github.com/zxdos/zxuno/issues/81 to find missing sources of the binary file needed to modify the credits. I can move on after closing that issue.

**Comment by ivan-tat** [comment]
Closed by https://github.com/zxdos/zxuno/pull/85
