### ISSUE TITLE
firmware/scroll: What is the real name of the musician?

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#76]
Who is the author of [`firmware/scroll/music.bin`](/zxdos/zxuno/blob/master/firmware/scroll/music.bin) file (aka *Yerzmyey*)? It is needed for accompanying `music.bin.license` file. If not a secret.

**Comment by antoniovillena** [comment]
His name is Michal B.
https://zxart.ee/eng/authors/y/yerzmyey/

**Comment by ivan-tat** [comment]
Thank you.

**Comment by ivan-tat** [comment]
Closed by fea6c0f304d3dc6f361810993f1dcf399adc5b77

**Comment by ivan-tat** [comment]
I searched the page https://zxart.ee/eng/authors/y/yerzmyey/ looking for the music [track](/zxdos/zxuno/blob/master/firmware/scroll/music.stc) used in demo and didn't find it in the list. What is the origin of this track?

**Comment by antoniovillena** [comment]
He sent us the track exclusively for this project

**Comment by ivan-tat** [comment]
Finally closed by 9b7b2efb6a01e60bfbdc6a50895ba7df914a33f2
