### ISSUE TITLE
firmware/scroll: Missing source of `playstc.bin` file

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#81]
File [`playstc.bin`](/zxdos/zxuno/blob/f6ed807bf9356b6423d83b2249cc78e9500307b3/firmware/scroll/playstc.bin) is a compiled binary file to play [`music.stc`](/zxdos/zxuno/blob/f6ed807bf9356b6423d83b2249cc78e9500307b3/firmware/scroll/music.stc). These files are joined together into a single [`music.bin`](/zxdos/zxuno/blob/f30c240e9a097f1cd9d175275cc9f5ca8ae5a29e/firmware/scroll/music.bin) file which is included into [`scroll.asm`](/zxdos/zxuno/blob/fea6c0f304d3dc6f361810993f1dcf399adc5b77/firmware/scroll/scroll.asm).

**Comment by ivan-tat** [comment]
If it was taken from somewhere else (a demo, I suppose) I suggest to use reverse-engineering to produce source file. I've already done this by using free software [`z80dasm`](https://www.tablix.org/~avian/blog/articles/z80dasm/) and tested it - everything works fine and the code is relocatable now (I can freely add any credits to the list). So, what do you think?

**Comment by antoniovillena** [comment]
I don't know where is the source. You can ask to him on his blog:
https://yerzmyey.bandcamp.com/

**Comment by ivan-tat** [comment]
I sent him a message via contact form from that site:

Subject:
>Help needed to find the source code

Message:
>Hi, Michal! I am a software developer contributing to ZX-Uno project - https://github.com/zxdos/zxuno
>Main developer, Antonio Villena, said that in 2016 you contributed a music track to this project in the form of a binary file "music.bin". I'm writing a script to automatically build the project from sources and I found that this file consists of a compiled source and a music itself. Here is an issue: https://github.com/zxdos/zxuno/issues/81
>Antonio redirected me to you in this question. In current state of the project I can't move on and stuck with absence of the source of "playstc.bin" file and I'm unable to modify the other source files without this one. Can you help us in finding the source code of this binary file?

Site's answer:
>Your message was sent to Yerzmyey.
>Please allow 5-7 business days for a response.

**Comment by ivan-tat** [comment]
He has lost the source code of his work. How about to **reconstruct** the source code out of the binary file?

**Comment by ivan-tat** [comment]
Added reverse-engineered sources for `playstc.bin` to compile `scroll.asm`. Closed by https://github.com/zxdos/zxuno/pull/84
