### ISSUE TITLE
firmware/scroll: Who are these "We" ?

### ISSUE THREAD

**Issue by ivan-tat** [zxdos/zxuno#82]
In the file [`string.asm`](/zxdos/zxuno/blob/edef405533b718151c1dc74264a77e5add65dc58/firmware/scroll/string.asm) at the start of the credits, you wrote (5th line):
```asm
        dz      $45, 'We want to thank all backers'
```
Who are these "**We**" ?

**Comment by antoniovillena** [comment]
The main team who created a legal association in Spain for the verkami crowdfunding (250 units of ZX-Uno) are:
McLeod (Miguel Ángel)
Me (Antonio Villena)
Hark0 (Jordi Bayó)
Quest (Samuel Baselga)

**Comment by ivan-tat** [comment]
Ok. Can I add these real names to the credits? It will be possible when we obtain sources of [`playstc.bin`](/zxdos/zxuno/blob/f6ed807bf9356b6423d83b2249cc78e9500307b3/firmware/scroll/playstc.bin) file (issue https://github.com/zxdos/zxuno/issues/81).

**Comment by ivan-tat** [comment]
It is now possible to modify the credits. If you want (and all agree) you can add these real names by yourself.
